[project]
name = "url-shortener-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gaurav5189", email = "gauravsethi4627@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]


[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "main:app"
